version: "2"
services:

  quiz_generator:
    build: .
    container_name: quiz
    command: flask run --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
    env_file: .env
    ports:
      - "5000:5000"
      - "5001:5001" # use for debugging
    volumes:
      - ./:/project
    stdin_open: true
    tty: true
    restart: always
    mem_limit: 4G
    env_file: .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    env_file: .env
    mem_limit: 2G
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      # add backup folder

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    env_file: .env
    mem_limit: 2G

  celery:
    build: .
    container_name: celery
    env_file: .env
    command: celery -A app.application:celery worker --loglevel=DEBUG --logfile=./logs/celery.log
    depends_on:
      - redis
      - quiz_generator
    volumes:
      - ./:/project
    stdin_open: true
    tty: true
    restart: always
    mem_limit: 1G

  celerybeat:
    build: .
    container_name: celerybeat
    env_file: .env
    command: celery -A app.application:celery beat --loglevel=DEBUG -s ./run/celerybeat-schedule --pidfile=./run/celerybeat.pid --logfile=./logs/celerybeat.log
    depends_on:
      - redis
      - quiz_generator
    volumes:
      - ./:/project
    stdin_open: true
    tty: true
    restart: always
    mem_limit: 500M
