version: "2"
services:

  quiz_generator:
    build: .
    container_name: quiz
    command: flask run --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    restart: always
    mem_limit: 4G
    env_file: .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    env_file: .env
    mem_limit: 2G
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    env_file: .env
    mem_limit: 2G
